#docker-compose file
version: "3.6"

services:
  docker-backend:
    container_name: backend
    build:
      dockerfile: dockerfileBackend
      context: .
    restart: always
    ports: 
      - 9897:9897
    expose: 
      - 9897
  docker-frontend:
    container_name: frontend
    build: 
      dockerfile: ./Dockerfile
      context: ../web
    restart: always
    ports: 
      - 8082:80
    expose: 
      - 8082