version: "3.6"
services: 
    web:
        container_name: web
        build: 
            dockerfile: Dockerfile
            context: .
        restart: always
        ports: 
            - 8082:80
        expose: 
            - 8082